"CREATE TABLE IF NOT EXISTS clients (
    client_id TEXT PRIMARY KEY,
    capacity INTEGER NOT NULL,
    rate_per_sec INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);"