FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o load-balancer ./cmd/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/load-balancer .
COPY config.yaml .
EXPOSE 8080
CMD ["./load-balancer"]