version: '3.8'

services:
  load-balancer:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      backend1:
        condition: service_healthy
      backend2:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend1:
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - ./backend1:/usr/share/nginx/html
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend2:
    image: nginx
    ports:
      - "8082:80"
    volumes:
      - ./backend2:/usr/share/nginx/html
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 3