version: '3.8'

services:
  load-balancer:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      backend1:
        condition: service_healthy
      backend2:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend1:
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - ./backend1:/usr/share/nginx/html
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: >
      sh -c "
      mkdir -p /usr/share/nginx/html &&
      echo 'Healthy' > /usr/share/nginx/html/health &&
      echo '<h1>Backend 1</h1>' > /usr/share/nginx/html/index.html &&
      exec nginx -g 'daemon off;'
      "

  backend2:
    image: nginx
    ports:
      - "8082:80"
    volumes:
      - ./backend2:/usr/share/nginx/html
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: >
      sh -c "
      mkdir -p /usr/share/nginx/html &&
      echo 'Healthy' > /usr/share/nginx/html/health &&
      echo '<h1>Backend 2</h1>' > /usr/share/nginx/html/index.html &&
      exec nginx -g 'daemon off;'
      "
  backend3:
    image: nginx
    ports:
      - "8083:80"
    volumes:
      - ./backend3:/usr/share/nginx/html
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: >
      sh -c "
      mkdir -p /usr/share/nginx/html &&
      echo 'Healthy' > /usr/share/nginx/html/health &&
      echo '<h1>Backend 3</h1>' > /usr/share/nginx/html/index.html &&
      exec nginx -g 'daemon off;'
      "